services:
  # UI镜像
  webui:
    image: renmu1234/bililive-tools-frontend
    ports:
      # 前者按需改动
      - "3000:3000"
  # 接口镜像
  api:
    image: renmu1234/bililive-tools-backend
    ports:
      - "18010:18010"
    volumes:
      # 映射的配置目录，用于持久化配置文件
      - ./data:/app/data
      # 存储文件的默认目录
      - ./video:/app/video
      # 字体目录
      - ./fonts:/usr/local/share/fonts
    environment:
      # 登录密钥
      - BILILIVE_TOOLS_PASSKEY=your_passkey
      # 账户加密密钥
      - BILILIVE_TOOLS_BILIKEY=your_bilikey
      # 中国时区
      - TZ=Asia/Shanghai
