name: build and push docker

on:
  # push:
  #   tags:
  #     - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/frontend-dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/bililive-tools-frontend:latest
            ${{ secrets.DOCKER_USERNAME }}/bililive-tools-frontend:${{ github.ref_name }}

      - name: Build and push backend image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/backend-dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/bililive-tools-backend:latest
            ${{ secrets.DOCKER_USERNAME }}/bililive-tools-backend:${{ github.ref_name }}

  manual-build:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/frontend-dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/bililive-tools-frontend:test

      - name: Build and push backend image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/backend-dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/bililive-tools-backend:test
