name: Build/release Electron app

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Cache Electron
        uses: actions/cache@v3
        with:
          path: ~\AppData\Local\electron\Cache
          key: ${{ runner.os }}-electron-cache-${{ hashFiles(format('{0}{1}', github.workspace, '/package-lock.json')) }}
          restore-keys: |
            ${{ runner.os }}-electron-cache-

      - name: Cache Electron-Builder
        uses: actions/cache@v3
        with:
          path: ~\AppData\Local\electron-builder\Cache
          key: ${{ runner.os }}-electron-builder-cache-${{ hashFiles(format('{0}{1}', github.workspace, '/package-lock.json')) }}
          restore-keys: |
            ${{ runner.os }}-electron-builder-cache-

      - name: Install Dependencies
        run: npm ci

      - name: Download File
        run: |
          # 使用 curl 下载文件
          curl -LJO  https://github.com/renmu123/biliLive-tools/releases/download/0.2.1/bin.zip

      - name: Extract File
        run: |
          # 使用 unzip 解压 ZIP 文件
          powershell Expand-Archive -Path bin.zip -DestinationPath resources

      - name: remove file
        run: |
          del bin.zip

      - name: build-win
        run: npm run build:win
      - name: build-win-no-ffmpeg
        run: npm run build:win-no-ffmpeg

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            dist/*.exe
            dist/*.zip
            dist/*.dmg
            dist/*.AppImage
            dist/*.snap
            dist/*.deb
            dist/*.rpm
            dist/*.tar.gz
            dist/*.yml
            dist/*.blockmap
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write
