name: build and push webui

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  release:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    env:
      is_tag: ${{ startsWith(github.ref, 'refs/tags/') }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: build
        run: pnpm run build:webui

      - name: Deploy to webui branch
        if: env.is_tag == 'true'
        env:
          REPO: https://github.com/renmu123/biliLive-webui
          BRANCH: webui
          GH_PAT: ${{ secrets.WEBUI_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          cd packages/app/out/renderer
          git init
          git remote add origin https://x-access-token:${GH_PAT}@github.com/renmu123/biliLive-webui.git
          git checkout -b $BRANCH
          git add .
          git commit -m "Deploy compiled files"
          git push --force origin $BRANCH

      - name: Deploy to test branch
        env:
          REPO: https://github.com/renmu123/biliLive-webui
          BRANCH: test
          GH_PAT: ${{ secrets.WEBUI_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          cd packages/app/out/renderer
          git init
          git remote add origin https://x-access-token:${GH_PAT}@github.com/renmu123/biliLive-webui.git
          git checkout -b $BRANCH
          git add .
          git commit -m "Deploy compiled files"
          git push --force origin $BRANCH

permissions:
  contents: write
